In [1]:
import pandas as pd

df = pd.read_csv('2_bookings.csv', sep=';')

In [2]:
# Узнаем размер таблицы

df.shape

(119390, 21)

In [3]:
# Посмотрим на типы переменных

df.dtypes

Hotel                         object
Is Canceled                    int64
Lead Time                      int64
arrival full date             object
Arrival Date Year              int64
Arrival Date Month            object
Arrival Date Week Number       int64
Arrival Date Day of Month      int64
Stays in Weekend nights        int64
Stays in week nights           int64
stays total nights             int64
Adults                         int64
Children                     float64
Babies                         int64
Meal                          object
Country                       object
Reserved Room Type            object
Assigned room type            object
customer type                 object
Reservation Status            object
Reservation status_date       object
dtype: object

In [4]:
# Выведем первые 7 строк

df.head(7)

,Hotel,Is Canceled,Lead Time,arrival full date,Arrival Date Year,Arrival Date Month,Arrival Date Week Number,Arrival Date Day of Month,Stays in Weekend nights,Stays in week nights,...,Adults,Children,Babies,Meal,Country,Reserved Room Type,Assigned room type,customer type,Reservation Status,Reservation status_date
0,Resort Hotel,0,342,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,C,Transient,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03
6,Resort Hotel,0,0,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-03

In [5]:
# Приведем названия столбцов к нижнему регистру
# Заменим пробелы в названиях на нижнее подчеркивание

df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')

In [6]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_full_date',
       'arrival_date_year', 'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'stays_total_nights', 'adults', 'children',
       'babies', 'meal', 'country', 'reserved_room_type', 'assigned_room_type',
       'customer_type', 'reservation_status', 'reservation_status_date'],
      dtype='object')

In [7]:
# Узнаем пользователи из каких стран совершили наибольшее число успешных бронирований.
# Выведем ТОП-5

top_countries = (df.query('is_canceled == 0')
.groupby('country', as_index=False)
.agg(count_booking=('is_canceled', 'count'))
.sort_values('count_booking', ascending=False)
.head())
top_countries

    country  count_booking
125     PRT          21071
57      GBR           9676
54      FRA           8481
50      ESP           6391
42      DEU           6069

In [8]:
# Узнаем на сколько ночей в среднем бронируют отели разных типов

mean_nights_at_hotel = (df.groupby('hotel', as_index=False)
.agg(mean_nights=('stays_total_nights', 'mean')))
mean_nights_at_hotel

          hotel  mean_nights
0    City Hotel     2.978142
1  Resort Hotel     4.318547

In [9]:
# Узнаем сколько раз тип номера, полученный клиентом, отличался от изначально забронированного

df.query('assigned_room_type != reserved_room_type').shape[0]

14917

In [10]:
# Узнаем на какой месяц чаще всего оформляли бронь в 2016 году

most_booking_month_2016 = (
    df.query('arrival_date_year == 2016')
    .groupby('arrival_date_month', as_index=False)
    .agg(count_booking=('hotel', 'count'))
    .sort_values('count_booking', ascending=False).head(1)
)
most_booking_month_2016

   arrival_date_month  count_booking
10            October           6203

In [11]:
# Узнаем на какой месяц чаще всего оформляли бронь в 2017 году

most_booking_month_2017 = (
    df.query('arrival_date_year == 2017')
    .groupby('arrival_date_month', as_index=False)
    .agg(count_booking=('hotel', 'count'))
    .sort_values('count_booking', ascending=False).head(1)
)
most_booking_month_2017

  arrival_date_month  count_booking
7                May           6313

In [12]:
# Узнаем на какой месяц бронирования отеля типа City Hotel отменялись чаще всего в 2015 году

df_canceled = (
    df.query("hotel == 'City Hotel' and is_canceled == 1")
    .groupby(['arrival_date_year', 'arrival_date_month'], as_index=False)['hotel'].count()
)
df_canceled_2015 = df_canceled.query('arrival_date_year == 2015').sort_values('hotel', ascending=False).head(1)
df_canceled_2015

   arrival_date_year arrival_date_month  hotel
5               2015          September   1543

In [13]:
# Узнаем на какой месяц бронирования отеля типа City Hotel отменялись чаще всего в 2016 году

df_canceled_2016 = df_canceled.query('arrival_date_year == 2016').sort_values('hotel', ascending=False).head(1)
df_canceled_2016

    arrival_date_year arrival_date_month  hotel
16               2016            October   1947

In [14]:
# Узнаем на какой месяц бронирования отеля типа City Hotel отменялись чаще всего в 2017 году

df_canceled_2017 = df_canceled.query('arrival_date_year == 2017').sort_values('hotel', ascending=False).head(1)
df_canceled_2017

    arrival_date_year arrival_date_month  hotel
25               2017                May   2217

In [17]:
# Найдем наибольшее среднее значение среди 'adults', 'children', 'babies'

df[['adults', 'children', 'babies']].mean().idxmax()

'adults'

In [25]:
# Создадим колнку total_kids
# Узнаем для отелей какого типа среднее значение total_kids оказалось наибольшим

df['total_kids'] = df['children'] + df['babies']
df.groupby('hotel', as_index=False)['total_kids'].mean().round(2).sort_values('total_kids', ascending=False)

          hotel  total_kids
1  Resort Hotel        0.14
0    City Hotel        0.10

In [36]:
# Создадим колонку has_kids
# Посчитаем Churn Rate - процент клиентов которые отменили бронирование. Проверим как связана эта метрика с наличием детей

df['has_kids'] = df['total_kids'] > 0
df.groupby('has_kids')['is_canceled'].mean().round(4) * 100

has_kids
False    37.22
True     34.92
Name: is_canceled, dtype: float64